// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/billc-dev/tuango-go/ent/complete"
	"github.com/billc-dev/tuango-go/ent/predicate"
	"github.com/billc-dev/tuango-go/ent/schema"
	"github.com/billc-dev/tuango-go/ent/user"
)

// CompleteUpdate is the builder for updating Complete entities.
type CompleteUpdate struct {
	config
	hooks     []Hook
	mutation  *CompleteMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CompleteUpdate builder.
func (cu *CompleteUpdate) Where(ps ...predicate.Complete) *CompleteUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetUserID sets the "user_id" field.
func (cu *CompleteUpdate) SetUserID(s string) *CompleteUpdate {
	cu.mutation.SetUserID(s)
	return cu
}

// SetTotal sets the "total" field.
func (cu *CompleteUpdate) SetTotal(f float64) *CompleteUpdate {
	cu.mutation.ResetTotal()
	cu.mutation.SetTotal(f)
	return cu
}

// AddTotal adds f to the "total" field.
func (cu *CompleteUpdate) AddTotal(f float64) *CompleteUpdate {
	cu.mutation.AddTotal(f)
	return cu
}

// SetAdmin sets the "admin" field.
func (cu *CompleteUpdate) SetAdmin(s string) *CompleteUpdate {
	cu.mutation.SetAdmin(s)
	return cu
}

// SetLinePay sets the "line_pay" field.
func (cu *CompleteUpdate) SetLinePay(b bool) *CompleteUpdate {
	cu.mutation.SetLinePay(b)
	return cu
}

// SetNillableLinePay sets the "line_pay" field if the given value is not nil.
func (cu *CompleteUpdate) SetNillableLinePay(b *bool) *CompleteUpdate {
	if b != nil {
		cu.SetLinePay(*b)
	}
	return cu
}

// SetConfirmed sets the "confirmed" field.
func (cu *CompleteUpdate) SetConfirmed(b bool) *CompleteUpdate {
	cu.mutation.SetConfirmed(b)
	return cu
}

// SetNillableConfirmed sets the "confirmed" field if the given value is not nil.
func (cu *CompleteUpdate) SetNillableConfirmed(b *bool) *CompleteUpdate {
	if b != nil {
		cu.SetConfirmed(*b)
	}
	return cu
}

// SetOrders sets the "orders" field.
func (cu *CompleteUpdate) SetOrders(so []schema.CompleteOrder) *CompleteUpdate {
	cu.mutation.SetOrders(so)
	return cu
}

// AppendOrders appends so to the "orders" field.
func (cu *CompleteUpdate) AppendOrders(so []schema.CompleteOrder) *CompleteUpdate {
	cu.mutation.AppendOrders(so)
	return cu
}

// SetCreatedAt sets the "created_at" field.
func (cu *CompleteUpdate) SetCreatedAt(t time.Time) *CompleteUpdate {
	cu.mutation.SetCreatedAt(t)
	return cu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cu *CompleteUpdate) SetNillableCreatedAt(t *time.Time) *CompleteUpdate {
	if t != nil {
		cu.SetCreatedAt(*t)
	}
	return cu
}

// SetUser sets the "user" edge to the User entity.
func (cu *CompleteUpdate) SetUser(u *User) *CompleteUpdate {
	return cu.SetUserID(u.ID)
}

// Mutation returns the CompleteMutation object of the builder.
func (cu *CompleteUpdate) Mutation() *CompleteMutation {
	return cu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (cu *CompleteUpdate) ClearUser() *CompleteUpdate {
	cu.mutation.ClearUser()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CompleteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CompleteUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CompleteUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CompleteUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CompleteUpdate) check() error {
	if _, ok := cu.mutation.UserID(); cu.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Complete.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (cu *CompleteUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CompleteUpdate {
	cu.modifiers = append(cu.modifiers, modifiers...)
	return cu
}

func (cu *CompleteUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(complete.Table, complete.Columns, sqlgraph.NewFieldSpec(complete.FieldID, field.TypeString))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Total(); ok {
		_spec.SetField(complete.FieldTotal, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.AddedTotal(); ok {
		_spec.AddField(complete.FieldTotal, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.Admin(); ok {
		_spec.SetField(complete.FieldAdmin, field.TypeString, value)
	}
	if value, ok := cu.mutation.LinePay(); ok {
		_spec.SetField(complete.FieldLinePay, field.TypeBool, value)
	}
	if value, ok := cu.mutation.Confirmed(); ok {
		_spec.SetField(complete.FieldConfirmed, field.TypeBool, value)
	}
	if value, ok := cu.mutation.Orders(); ok {
		_spec.SetField(complete.FieldOrders, field.TypeJSON, value)
	}
	if value, ok := cu.mutation.AppendedOrders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, complete.FieldOrders, value)
		})
	}
	if value, ok := cu.mutation.CreatedAt(); ok {
		_spec.SetField(complete.FieldCreatedAt, field.TypeTime, value)
	}
	if cu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   complete.UserTable,
			Columns: []string{complete.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   complete.UserTable,
			Columns: []string{complete.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(cu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{complete.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CompleteUpdateOne is the builder for updating a single Complete entity.
type CompleteUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CompleteMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (cuo *CompleteUpdateOne) SetUserID(s string) *CompleteUpdateOne {
	cuo.mutation.SetUserID(s)
	return cuo
}

// SetTotal sets the "total" field.
func (cuo *CompleteUpdateOne) SetTotal(f float64) *CompleteUpdateOne {
	cuo.mutation.ResetTotal()
	cuo.mutation.SetTotal(f)
	return cuo
}

// AddTotal adds f to the "total" field.
func (cuo *CompleteUpdateOne) AddTotal(f float64) *CompleteUpdateOne {
	cuo.mutation.AddTotal(f)
	return cuo
}

// SetAdmin sets the "admin" field.
func (cuo *CompleteUpdateOne) SetAdmin(s string) *CompleteUpdateOne {
	cuo.mutation.SetAdmin(s)
	return cuo
}

// SetLinePay sets the "line_pay" field.
func (cuo *CompleteUpdateOne) SetLinePay(b bool) *CompleteUpdateOne {
	cuo.mutation.SetLinePay(b)
	return cuo
}

// SetNillableLinePay sets the "line_pay" field if the given value is not nil.
func (cuo *CompleteUpdateOne) SetNillableLinePay(b *bool) *CompleteUpdateOne {
	if b != nil {
		cuo.SetLinePay(*b)
	}
	return cuo
}

// SetConfirmed sets the "confirmed" field.
func (cuo *CompleteUpdateOne) SetConfirmed(b bool) *CompleteUpdateOne {
	cuo.mutation.SetConfirmed(b)
	return cuo
}

// SetNillableConfirmed sets the "confirmed" field if the given value is not nil.
func (cuo *CompleteUpdateOne) SetNillableConfirmed(b *bool) *CompleteUpdateOne {
	if b != nil {
		cuo.SetConfirmed(*b)
	}
	return cuo
}

// SetOrders sets the "orders" field.
func (cuo *CompleteUpdateOne) SetOrders(so []schema.CompleteOrder) *CompleteUpdateOne {
	cuo.mutation.SetOrders(so)
	return cuo
}

// AppendOrders appends so to the "orders" field.
func (cuo *CompleteUpdateOne) AppendOrders(so []schema.CompleteOrder) *CompleteUpdateOne {
	cuo.mutation.AppendOrders(so)
	return cuo
}

// SetCreatedAt sets the "created_at" field.
func (cuo *CompleteUpdateOne) SetCreatedAt(t time.Time) *CompleteUpdateOne {
	cuo.mutation.SetCreatedAt(t)
	return cuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cuo *CompleteUpdateOne) SetNillableCreatedAt(t *time.Time) *CompleteUpdateOne {
	if t != nil {
		cuo.SetCreatedAt(*t)
	}
	return cuo
}

// SetUser sets the "user" edge to the User entity.
func (cuo *CompleteUpdateOne) SetUser(u *User) *CompleteUpdateOne {
	return cuo.SetUserID(u.ID)
}

// Mutation returns the CompleteMutation object of the builder.
func (cuo *CompleteUpdateOne) Mutation() *CompleteMutation {
	return cuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (cuo *CompleteUpdateOne) ClearUser() *CompleteUpdateOne {
	cuo.mutation.ClearUser()
	return cuo
}

// Where appends a list predicates to the CompleteUpdate builder.
func (cuo *CompleteUpdateOne) Where(ps ...predicate.Complete) *CompleteUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CompleteUpdateOne) Select(field string, fields ...string) *CompleteUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Complete entity.
func (cuo *CompleteUpdateOne) Save(ctx context.Context) (*Complete, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CompleteUpdateOne) SaveX(ctx context.Context) *Complete {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CompleteUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CompleteUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CompleteUpdateOne) check() error {
	if _, ok := cuo.mutation.UserID(); cuo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Complete.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (cuo *CompleteUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CompleteUpdateOne {
	cuo.modifiers = append(cuo.modifiers, modifiers...)
	return cuo
}

func (cuo *CompleteUpdateOne) sqlSave(ctx context.Context) (_node *Complete, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(complete.Table, complete.Columns, sqlgraph.NewFieldSpec(complete.FieldID, field.TypeString))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Complete.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, complete.FieldID)
		for _, f := range fields {
			if !complete.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != complete.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Total(); ok {
		_spec.SetField(complete.FieldTotal, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.AddedTotal(); ok {
		_spec.AddField(complete.FieldTotal, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.Admin(); ok {
		_spec.SetField(complete.FieldAdmin, field.TypeString, value)
	}
	if value, ok := cuo.mutation.LinePay(); ok {
		_spec.SetField(complete.FieldLinePay, field.TypeBool, value)
	}
	if value, ok := cuo.mutation.Confirmed(); ok {
		_spec.SetField(complete.FieldConfirmed, field.TypeBool, value)
	}
	if value, ok := cuo.mutation.Orders(); ok {
		_spec.SetField(complete.FieldOrders, field.TypeJSON, value)
	}
	if value, ok := cuo.mutation.AppendedOrders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, complete.FieldOrders, value)
		})
	}
	if value, ok := cuo.mutation.CreatedAt(); ok {
		_spec.SetField(complete.FieldCreatedAt, field.TypeTime, value)
	}
	if cuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   complete.UserTable,
			Columns: []string{complete.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   complete.UserTable,
			Columns: []string{complete.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(cuo.modifiers...)
	_node = &Complete{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{complete.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
