// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/billc-dev/tuango-go/ent/order"
	"github.com/billc-dev/tuango-go/ent/orderhistory"
	"github.com/billc-dev/tuango-go/ent/predicate"
)

// OrderHistoryUpdate is the builder for updating OrderHistory entities.
type OrderHistoryUpdate struct {
	config
	hooks     []Hook
	mutation  *OrderHistoryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the OrderHistoryUpdate builder.
func (ohu *OrderHistoryUpdate) Where(ps ...predicate.OrderHistory) *OrderHistoryUpdate {
	ohu.mutation.Where(ps...)
	return ohu
}

// SetOrderID sets the "order_id" field.
func (ohu *OrderHistoryUpdate) SetOrderID(s string) *OrderHistoryUpdate {
	ohu.mutation.SetOrderID(s)
	return ohu
}

// SetStatus sets the "status" field.
func (ohu *OrderHistoryUpdate) SetStatus(o orderhistory.Status) *OrderHistoryUpdate {
	ohu.mutation.SetStatus(o)
	return ohu
}

// SetCreatedAt sets the "created_at" field.
func (ohu *OrderHistoryUpdate) SetCreatedAt(t time.Time) *OrderHistoryUpdate {
	ohu.mutation.SetCreatedAt(t)
	return ohu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ohu *OrderHistoryUpdate) SetNillableCreatedAt(t *time.Time) *OrderHistoryUpdate {
	if t != nil {
		ohu.SetCreatedAt(*t)
	}
	return ohu
}

// SetOrder sets the "order" edge to the Order entity.
func (ohu *OrderHistoryUpdate) SetOrder(o *Order) *OrderHistoryUpdate {
	return ohu.SetOrderID(o.ID)
}

// Mutation returns the OrderHistoryMutation object of the builder.
func (ohu *OrderHistoryUpdate) Mutation() *OrderHistoryMutation {
	return ohu.mutation
}

// ClearOrder clears the "order" edge to the Order entity.
func (ohu *OrderHistoryUpdate) ClearOrder() *OrderHistoryUpdate {
	ohu.mutation.ClearOrder()
	return ohu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ohu *OrderHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ohu.sqlSave, ohu.mutation, ohu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ohu *OrderHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := ohu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ohu *OrderHistoryUpdate) Exec(ctx context.Context) error {
	_, err := ohu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ohu *OrderHistoryUpdate) ExecX(ctx context.Context) {
	if err := ohu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ohu *OrderHistoryUpdate) check() error {
	if v, ok := ohu.mutation.Status(); ok {
		if err := orderhistory.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OrderHistory.status": %w`, err)}
		}
	}
	if _, ok := ohu.mutation.OrderID(); ohu.mutation.OrderCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "OrderHistory.order"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ohu *OrderHistoryUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OrderHistoryUpdate {
	ohu.modifiers = append(ohu.modifiers, modifiers...)
	return ohu
}

func (ohu *OrderHistoryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ohu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderhistory.Table, orderhistory.Columns, sqlgraph.NewFieldSpec(orderhistory.FieldID, field.TypeString))
	if ps := ohu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ohu.mutation.Status(); ok {
		_spec.SetField(orderhistory.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := ohu.mutation.CreatedAt(); ok {
		_spec.SetField(orderhistory.FieldCreatedAt, field.TypeTime, value)
	}
	if ohu.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderhistory.OrderTable,
			Columns: []string{orderhistory.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ohu.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderhistory.OrderTable,
			Columns: []string{orderhistory.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(ohu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, ohu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ohu.mutation.done = true
	return n, nil
}

// OrderHistoryUpdateOne is the builder for updating a single OrderHistory entity.
type OrderHistoryUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *OrderHistoryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetOrderID sets the "order_id" field.
func (ohuo *OrderHistoryUpdateOne) SetOrderID(s string) *OrderHistoryUpdateOne {
	ohuo.mutation.SetOrderID(s)
	return ohuo
}

// SetStatus sets the "status" field.
func (ohuo *OrderHistoryUpdateOne) SetStatus(o orderhistory.Status) *OrderHistoryUpdateOne {
	ohuo.mutation.SetStatus(o)
	return ohuo
}

// SetCreatedAt sets the "created_at" field.
func (ohuo *OrderHistoryUpdateOne) SetCreatedAt(t time.Time) *OrderHistoryUpdateOne {
	ohuo.mutation.SetCreatedAt(t)
	return ohuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ohuo *OrderHistoryUpdateOne) SetNillableCreatedAt(t *time.Time) *OrderHistoryUpdateOne {
	if t != nil {
		ohuo.SetCreatedAt(*t)
	}
	return ohuo
}

// SetOrder sets the "order" edge to the Order entity.
func (ohuo *OrderHistoryUpdateOne) SetOrder(o *Order) *OrderHistoryUpdateOne {
	return ohuo.SetOrderID(o.ID)
}

// Mutation returns the OrderHistoryMutation object of the builder.
func (ohuo *OrderHistoryUpdateOne) Mutation() *OrderHistoryMutation {
	return ohuo.mutation
}

// ClearOrder clears the "order" edge to the Order entity.
func (ohuo *OrderHistoryUpdateOne) ClearOrder() *OrderHistoryUpdateOne {
	ohuo.mutation.ClearOrder()
	return ohuo
}

// Where appends a list predicates to the OrderHistoryUpdate builder.
func (ohuo *OrderHistoryUpdateOne) Where(ps ...predicate.OrderHistory) *OrderHistoryUpdateOne {
	ohuo.mutation.Where(ps...)
	return ohuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ohuo *OrderHistoryUpdateOne) Select(field string, fields ...string) *OrderHistoryUpdateOne {
	ohuo.fields = append([]string{field}, fields...)
	return ohuo
}

// Save executes the query and returns the updated OrderHistory entity.
func (ohuo *OrderHistoryUpdateOne) Save(ctx context.Context) (*OrderHistory, error) {
	return withHooks(ctx, ohuo.sqlSave, ohuo.mutation, ohuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ohuo *OrderHistoryUpdateOne) SaveX(ctx context.Context) *OrderHistory {
	node, err := ohuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ohuo *OrderHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := ohuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ohuo *OrderHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := ohuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ohuo *OrderHistoryUpdateOne) check() error {
	if v, ok := ohuo.mutation.Status(); ok {
		if err := orderhistory.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OrderHistory.status": %w`, err)}
		}
	}
	if _, ok := ohuo.mutation.OrderID(); ohuo.mutation.OrderCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "OrderHistory.order"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ohuo *OrderHistoryUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OrderHistoryUpdateOne {
	ohuo.modifiers = append(ohuo.modifiers, modifiers...)
	return ohuo
}

func (ohuo *OrderHistoryUpdateOne) sqlSave(ctx context.Context) (_node *OrderHistory, err error) {
	if err := ohuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderhistory.Table, orderhistory.Columns, sqlgraph.NewFieldSpec(orderhistory.FieldID, field.TypeString))
	id, ok := ohuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrderHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ohuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderhistory.FieldID)
		for _, f := range fields {
			if !orderhistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != orderhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ohuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ohuo.mutation.Status(); ok {
		_spec.SetField(orderhistory.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := ohuo.mutation.CreatedAt(); ok {
		_spec.SetField(orderhistory.FieldCreatedAt, field.TypeTime, value)
	}
	if ohuo.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderhistory.OrderTable,
			Columns: []string{orderhistory.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ohuo.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderhistory.OrderTable,
			Columns: []string{orderhistory.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(ohuo.modifiers...)
	_node = &OrderHistory{config: ohuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ohuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ohuo.mutation.done = true
	return _node, nil
}
