// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/billc-dev/tuango-go/ent/order"
	"github.com/billc-dev/tuango-go/ent/orderhistory"
	"github.com/billc-dev/tuango-go/ent/orderitem"
	"github.com/billc-dev/tuango-go/ent/post"
	"github.com/billc-dev/tuango-go/ent/predicate"
	"github.com/billc-dev/tuango-go/ent/user"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks     []Hook
	mutation  *OrderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the OrderUpdate builder.
func (ou *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetUserID sets the "user_id" field.
func (ou *OrderUpdate) SetUserID(s string) *OrderUpdate {
	ou.mutation.SetUserID(s)
	return ou
}

// SetPostID sets the "post_id" field.
func (ou *OrderUpdate) SetPostID(s string) *OrderUpdate {
	ou.mutation.SetPostID(s)
	return ou
}

// SetOrderNum sets the "order_num" field.
func (ou *OrderUpdate) SetOrderNum(i int) *OrderUpdate {
	ou.mutation.ResetOrderNum()
	ou.mutation.SetOrderNum(i)
	return ou
}

// AddOrderNum adds i to the "order_num" field.
func (ou *OrderUpdate) AddOrderNum(i int) *OrderUpdate {
	ou.mutation.AddOrderNum(i)
	return ou
}

// SetComment sets the "comment" field.
func (ou *OrderUpdate) SetComment(s string) *OrderUpdate {
	ou.mutation.SetComment(s)
	return ou
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableComment(s *string) *OrderUpdate {
	if s != nil {
		ou.SetComment(*s)
	}
	return ou
}

// SetSellerComment sets the "seller_comment" field.
func (ou *OrderUpdate) SetSellerComment(s string) *OrderUpdate {
	ou.mutation.SetSellerComment(s)
	return ou
}

// SetNillableSellerComment sets the "seller_comment" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableSellerComment(s *string) *OrderUpdate {
	if s != nil {
		ou.SetSellerComment(*s)
	}
	return ou
}

// SetHasName sets the "has_name" field.
func (ou *OrderUpdate) SetHasName(b bool) *OrderUpdate {
	ou.mutation.SetHasName(b)
	return ou
}

// SetNillableHasName sets the "has_name" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableHasName(b *bool) *OrderUpdate {
	if b != nil {
		ou.SetHasName(*b)
	}
	return ou
}

// SetIsExtra sets the "is_extra" field.
func (ou *OrderUpdate) SetIsExtra(b bool) *OrderUpdate {
	ou.mutation.SetIsExtra(b)
	return ou
}

// SetNillableIsExtra sets the "is_extra" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableIsExtra(b *bool) *OrderUpdate {
	if b != nil {
		ou.SetIsExtra(*b)
	}
	return ou
}

// SetFb sets the "fb" field.
func (ou *OrderUpdate) SetFb(b bool) *OrderUpdate {
	ou.mutation.SetFb(b)
	return ou
}

// SetNillableFb sets the "fb" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableFb(b *bool) *OrderUpdate {
	if b != nil {
		ou.SetFb(*b)
	}
	return ou
}

// SetIsInStock sets the "is_in_stock" field.
func (ou *OrderUpdate) SetIsInStock(b bool) *OrderUpdate {
	ou.mutation.SetIsInStock(b)
	return ou
}

// SetNillableIsInStock sets the "is_in_stock" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableIsInStock(b *bool) *OrderUpdate {
	if b != nil {
		ou.SetIsInStock(*b)
	}
	return ou
}

// SetStatus sets the "status" field.
func (ou *OrderUpdate) SetStatus(o order.Status) *OrderUpdate {
	ou.mutation.SetStatus(o)
	return ou
}

// SetCreatedAt sets the "created_at" field.
func (ou *OrderUpdate) SetCreatedAt(t time.Time) *OrderUpdate {
	ou.mutation.SetCreatedAt(t)
	return ou
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableCreatedAt(t *time.Time) *OrderUpdate {
	if t != nil {
		ou.SetCreatedAt(*t)
	}
	return ou
}

// SetUpdatedAt sets the "updated_at" field.
func (ou *OrderUpdate) SetUpdatedAt(t time.Time) *OrderUpdate {
	ou.mutation.SetUpdatedAt(t)
	return ou
}

// SetUser sets the "user" edge to the User entity.
func (ou *OrderUpdate) SetUser(u *User) *OrderUpdate {
	return ou.SetUserID(u.ID)
}

// SetPost sets the "post" edge to the Post entity.
func (ou *OrderUpdate) SetPost(p *Post) *OrderUpdate {
	return ou.SetPostID(p.ID)
}

// AddOrderItemIDs adds the "order_items" edge to the OrderItem entity by IDs.
func (ou *OrderUpdate) AddOrderItemIDs(ids ...string) *OrderUpdate {
	ou.mutation.AddOrderItemIDs(ids...)
	return ou
}

// AddOrderItems adds the "order_items" edges to the OrderItem entity.
func (ou *OrderUpdate) AddOrderItems(o ...*OrderItem) *OrderUpdate {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ou.AddOrderItemIDs(ids...)
}

// AddOrderHistoryIDs adds the "order_histories" edge to the OrderHistory entity by IDs.
func (ou *OrderUpdate) AddOrderHistoryIDs(ids ...string) *OrderUpdate {
	ou.mutation.AddOrderHistoryIDs(ids...)
	return ou
}

// AddOrderHistories adds the "order_histories" edges to the OrderHistory entity.
func (ou *OrderUpdate) AddOrderHistories(o ...*OrderHistory) *OrderUpdate {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ou.AddOrderHistoryIDs(ids...)
}

// Mutation returns the OrderMutation object of the builder.
func (ou *OrderUpdate) Mutation() *OrderMutation {
	return ou.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ou *OrderUpdate) ClearUser() *OrderUpdate {
	ou.mutation.ClearUser()
	return ou
}

// ClearPost clears the "post" edge to the Post entity.
func (ou *OrderUpdate) ClearPost() *OrderUpdate {
	ou.mutation.ClearPost()
	return ou
}

// ClearOrderItems clears all "order_items" edges to the OrderItem entity.
func (ou *OrderUpdate) ClearOrderItems() *OrderUpdate {
	ou.mutation.ClearOrderItems()
	return ou
}

// RemoveOrderItemIDs removes the "order_items" edge to OrderItem entities by IDs.
func (ou *OrderUpdate) RemoveOrderItemIDs(ids ...string) *OrderUpdate {
	ou.mutation.RemoveOrderItemIDs(ids...)
	return ou
}

// RemoveOrderItems removes "order_items" edges to OrderItem entities.
func (ou *OrderUpdate) RemoveOrderItems(o ...*OrderItem) *OrderUpdate {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ou.RemoveOrderItemIDs(ids...)
}

// ClearOrderHistories clears all "order_histories" edges to the OrderHistory entity.
func (ou *OrderUpdate) ClearOrderHistories() *OrderUpdate {
	ou.mutation.ClearOrderHistories()
	return ou
}

// RemoveOrderHistoryIDs removes the "order_histories" edge to OrderHistory entities by IDs.
func (ou *OrderUpdate) RemoveOrderHistoryIDs(ids ...string) *OrderUpdate {
	ou.mutation.RemoveOrderHistoryIDs(ids...)
	return ou
}

// RemoveOrderHistories removes "order_histories" edges to OrderHistory entities.
func (ou *OrderUpdate) RemoveOrderHistories(o ...*OrderHistory) *OrderUpdate {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ou.RemoveOrderHistoryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OrderUpdate) Save(ctx context.Context) (int, error) {
	ou.defaults()
	return withHooks(ctx, ou.sqlSave, ou.mutation, ou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OrderUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OrderUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ou *OrderUpdate) defaults() {
	if _, ok := ou.mutation.UpdatedAt(); !ok {
		v := order.UpdateDefaultUpdatedAt()
		ou.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ou *OrderUpdate) check() error {
	if v, ok := ou.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	if _, ok := ou.mutation.UserID(); ou.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Order.user"`)
	}
	if _, ok := ou.mutation.PostID(); ou.mutation.PostCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Order.post"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ou *OrderUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OrderUpdate {
	ou.modifiers = append(ou.modifiers, modifiers...)
	return ou
}

func (ou *OrderUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ou.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeString))
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.OrderNum(); ok {
		_spec.SetField(order.FieldOrderNum, field.TypeInt, value)
	}
	if value, ok := ou.mutation.AddedOrderNum(); ok {
		_spec.AddField(order.FieldOrderNum, field.TypeInt, value)
	}
	if value, ok := ou.mutation.Comment(); ok {
		_spec.SetField(order.FieldComment, field.TypeString, value)
	}
	if value, ok := ou.mutation.SellerComment(); ok {
		_spec.SetField(order.FieldSellerComment, field.TypeString, value)
	}
	if value, ok := ou.mutation.HasName(); ok {
		_spec.SetField(order.FieldHasName, field.TypeBool, value)
	}
	if value, ok := ou.mutation.IsExtra(); ok {
		_spec.SetField(order.FieldIsExtra, field.TypeBool, value)
	}
	if value, ok := ou.mutation.Fb(); ok {
		_spec.SetField(order.FieldFb, field.TypeBool, value)
	}
	if value, ok := ou.mutation.IsInStock(); ok {
		_spec.SetField(order.FieldIsInStock, field.TypeBool, value)
	}
	if value, ok := ou.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := ou.mutation.CreatedAt(); ok {
		_spec.SetField(order.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := ou.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if ou.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ou.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.PostTable,
			Columns: []string{order.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.PostTable,
			Columns: []string{order.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ou.mutation.OrderItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.OrderItemsTable,
			Columns: []string{order.OrderItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.RemovedOrderItemsIDs(); len(nodes) > 0 && !ou.mutation.OrderItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.OrderItemsTable,
			Columns: []string{order.OrderItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.OrderItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.OrderItemsTable,
			Columns: []string{order.OrderItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ou.mutation.OrderHistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.OrderHistoriesTable,
			Columns: []string{order.OrderHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderhistory.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.RemovedOrderHistoriesIDs(); len(nodes) > 0 && !ou.mutation.OrderHistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.OrderHistoriesTable,
			Columns: []string{order.OrderHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderhistory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.OrderHistoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.OrderHistoriesTable,
			Columns: []string{order.OrderHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderhistory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(ou.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ou.mutation.done = true
	return n, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *OrderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (ouo *OrderUpdateOne) SetUserID(s string) *OrderUpdateOne {
	ouo.mutation.SetUserID(s)
	return ouo
}

// SetPostID sets the "post_id" field.
func (ouo *OrderUpdateOne) SetPostID(s string) *OrderUpdateOne {
	ouo.mutation.SetPostID(s)
	return ouo
}

// SetOrderNum sets the "order_num" field.
func (ouo *OrderUpdateOne) SetOrderNum(i int) *OrderUpdateOne {
	ouo.mutation.ResetOrderNum()
	ouo.mutation.SetOrderNum(i)
	return ouo
}

// AddOrderNum adds i to the "order_num" field.
func (ouo *OrderUpdateOne) AddOrderNum(i int) *OrderUpdateOne {
	ouo.mutation.AddOrderNum(i)
	return ouo
}

// SetComment sets the "comment" field.
func (ouo *OrderUpdateOne) SetComment(s string) *OrderUpdateOne {
	ouo.mutation.SetComment(s)
	return ouo
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableComment(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetComment(*s)
	}
	return ouo
}

// SetSellerComment sets the "seller_comment" field.
func (ouo *OrderUpdateOne) SetSellerComment(s string) *OrderUpdateOne {
	ouo.mutation.SetSellerComment(s)
	return ouo
}

// SetNillableSellerComment sets the "seller_comment" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableSellerComment(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetSellerComment(*s)
	}
	return ouo
}

// SetHasName sets the "has_name" field.
func (ouo *OrderUpdateOne) SetHasName(b bool) *OrderUpdateOne {
	ouo.mutation.SetHasName(b)
	return ouo
}

// SetNillableHasName sets the "has_name" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableHasName(b *bool) *OrderUpdateOne {
	if b != nil {
		ouo.SetHasName(*b)
	}
	return ouo
}

// SetIsExtra sets the "is_extra" field.
func (ouo *OrderUpdateOne) SetIsExtra(b bool) *OrderUpdateOne {
	ouo.mutation.SetIsExtra(b)
	return ouo
}

// SetNillableIsExtra sets the "is_extra" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableIsExtra(b *bool) *OrderUpdateOne {
	if b != nil {
		ouo.SetIsExtra(*b)
	}
	return ouo
}

// SetFb sets the "fb" field.
func (ouo *OrderUpdateOne) SetFb(b bool) *OrderUpdateOne {
	ouo.mutation.SetFb(b)
	return ouo
}

// SetNillableFb sets the "fb" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableFb(b *bool) *OrderUpdateOne {
	if b != nil {
		ouo.SetFb(*b)
	}
	return ouo
}

// SetIsInStock sets the "is_in_stock" field.
func (ouo *OrderUpdateOne) SetIsInStock(b bool) *OrderUpdateOne {
	ouo.mutation.SetIsInStock(b)
	return ouo
}

// SetNillableIsInStock sets the "is_in_stock" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableIsInStock(b *bool) *OrderUpdateOne {
	if b != nil {
		ouo.SetIsInStock(*b)
	}
	return ouo
}

// SetStatus sets the "status" field.
func (ouo *OrderUpdateOne) SetStatus(o order.Status) *OrderUpdateOne {
	ouo.mutation.SetStatus(o)
	return ouo
}

// SetCreatedAt sets the "created_at" field.
func (ouo *OrderUpdateOne) SetCreatedAt(t time.Time) *OrderUpdateOne {
	ouo.mutation.SetCreatedAt(t)
	return ouo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableCreatedAt(t *time.Time) *OrderUpdateOne {
	if t != nil {
		ouo.SetCreatedAt(*t)
	}
	return ouo
}

// SetUpdatedAt sets the "updated_at" field.
func (ouo *OrderUpdateOne) SetUpdatedAt(t time.Time) *OrderUpdateOne {
	ouo.mutation.SetUpdatedAt(t)
	return ouo
}

// SetUser sets the "user" edge to the User entity.
func (ouo *OrderUpdateOne) SetUser(u *User) *OrderUpdateOne {
	return ouo.SetUserID(u.ID)
}

// SetPost sets the "post" edge to the Post entity.
func (ouo *OrderUpdateOne) SetPost(p *Post) *OrderUpdateOne {
	return ouo.SetPostID(p.ID)
}

// AddOrderItemIDs adds the "order_items" edge to the OrderItem entity by IDs.
func (ouo *OrderUpdateOne) AddOrderItemIDs(ids ...string) *OrderUpdateOne {
	ouo.mutation.AddOrderItemIDs(ids...)
	return ouo
}

// AddOrderItems adds the "order_items" edges to the OrderItem entity.
func (ouo *OrderUpdateOne) AddOrderItems(o ...*OrderItem) *OrderUpdateOne {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ouo.AddOrderItemIDs(ids...)
}

// AddOrderHistoryIDs adds the "order_histories" edge to the OrderHistory entity by IDs.
func (ouo *OrderUpdateOne) AddOrderHistoryIDs(ids ...string) *OrderUpdateOne {
	ouo.mutation.AddOrderHistoryIDs(ids...)
	return ouo
}

// AddOrderHistories adds the "order_histories" edges to the OrderHistory entity.
func (ouo *OrderUpdateOne) AddOrderHistories(o ...*OrderHistory) *OrderUpdateOne {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ouo.AddOrderHistoryIDs(ids...)
}

// Mutation returns the OrderMutation object of the builder.
func (ouo *OrderUpdateOne) Mutation() *OrderMutation {
	return ouo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ouo *OrderUpdateOne) ClearUser() *OrderUpdateOne {
	ouo.mutation.ClearUser()
	return ouo
}

// ClearPost clears the "post" edge to the Post entity.
func (ouo *OrderUpdateOne) ClearPost() *OrderUpdateOne {
	ouo.mutation.ClearPost()
	return ouo
}

// ClearOrderItems clears all "order_items" edges to the OrderItem entity.
func (ouo *OrderUpdateOne) ClearOrderItems() *OrderUpdateOne {
	ouo.mutation.ClearOrderItems()
	return ouo
}

// RemoveOrderItemIDs removes the "order_items" edge to OrderItem entities by IDs.
func (ouo *OrderUpdateOne) RemoveOrderItemIDs(ids ...string) *OrderUpdateOne {
	ouo.mutation.RemoveOrderItemIDs(ids...)
	return ouo
}

// RemoveOrderItems removes "order_items" edges to OrderItem entities.
func (ouo *OrderUpdateOne) RemoveOrderItems(o ...*OrderItem) *OrderUpdateOne {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ouo.RemoveOrderItemIDs(ids...)
}

// ClearOrderHistories clears all "order_histories" edges to the OrderHistory entity.
func (ouo *OrderUpdateOne) ClearOrderHistories() *OrderUpdateOne {
	ouo.mutation.ClearOrderHistories()
	return ouo
}

// RemoveOrderHistoryIDs removes the "order_histories" edge to OrderHistory entities by IDs.
func (ouo *OrderUpdateOne) RemoveOrderHistoryIDs(ids ...string) *OrderUpdateOne {
	ouo.mutation.RemoveOrderHistoryIDs(ids...)
	return ouo
}

// RemoveOrderHistories removes "order_histories" edges to OrderHistory entities.
func (ouo *OrderUpdateOne) RemoveOrderHistories(o ...*OrderHistory) *OrderUpdateOne {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ouo.RemoveOrderHistoryIDs(ids...)
}

// Where appends a list predicates to the OrderUpdate builder.
func (ouo *OrderUpdateOne) Where(ps ...predicate.Order) *OrderUpdateOne {
	ouo.mutation.Where(ps...)
	return ouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated Order entity.
func (ouo *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	ouo.defaults()
	return withHooks(ctx, ouo.sqlSave, ouo.mutation, ouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ouo *OrderUpdateOne) defaults() {
	if _, ok := ouo.mutation.UpdatedAt(); !ok {
		v := order.UpdateDefaultUpdatedAt()
		ouo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ouo *OrderUpdateOne) check() error {
	if v, ok := ouo.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	if _, ok := ouo.mutation.UserID(); ouo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Order.user"`)
	}
	if _, ok := ouo.mutation.PostID(); ouo.mutation.PostCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Order.post"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ouo *OrderUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OrderUpdateOne {
	ouo.modifiers = append(ouo.modifiers, modifiers...)
	return ouo
}

func (ouo *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	if err := ouo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeString))
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.OrderNum(); ok {
		_spec.SetField(order.FieldOrderNum, field.TypeInt, value)
	}
	if value, ok := ouo.mutation.AddedOrderNum(); ok {
		_spec.AddField(order.FieldOrderNum, field.TypeInt, value)
	}
	if value, ok := ouo.mutation.Comment(); ok {
		_spec.SetField(order.FieldComment, field.TypeString, value)
	}
	if value, ok := ouo.mutation.SellerComment(); ok {
		_spec.SetField(order.FieldSellerComment, field.TypeString, value)
	}
	if value, ok := ouo.mutation.HasName(); ok {
		_spec.SetField(order.FieldHasName, field.TypeBool, value)
	}
	if value, ok := ouo.mutation.IsExtra(); ok {
		_spec.SetField(order.FieldIsExtra, field.TypeBool, value)
	}
	if value, ok := ouo.mutation.Fb(); ok {
		_spec.SetField(order.FieldFb, field.TypeBool, value)
	}
	if value, ok := ouo.mutation.IsInStock(); ok {
		_spec.SetField(order.FieldIsInStock, field.TypeBool, value)
	}
	if value, ok := ouo.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := ouo.mutation.CreatedAt(); ok {
		_spec.SetField(order.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := ouo.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if ouo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ouo.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.PostTable,
			Columns: []string{order.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.PostTable,
			Columns: []string{order.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ouo.mutation.OrderItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.OrderItemsTable,
			Columns: []string{order.OrderItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.RemovedOrderItemsIDs(); len(nodes) > 0 && !ouo.mutation.OrderItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.OrderItemsTable,
			Columns: []string{order.OrderItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.OrderItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.OrderItemsTable,
			Columns: []string{order.OrderItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ouo.mutation.OrderHistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.OrderHistoriesTable,
			Columns: []string{order.OrderHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderhistory.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.RemovedOrderHistoriesIDs(); len(nodes) > 0 && !ouo.mutation.OrderHistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.OrderHistoriesTable,
			Columns: []string{order.OrderHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderhistory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.OrderHistoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.OrderHistoriesTable,
			Columns: []string{order.OrderHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderhistory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(ouo.modifiers...)
	_node = &Order{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouo.mutation.done = true
	return _node, nil
}
