// Code generated by ent, DO NOT EDIT.

package deliver

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the deliver type in the database.
	Label = "deliver"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPostID holds the string denoting the post_id field in the database.
	FieldPostID = "post_id"
	// FieldNormalOrders holds the string denoting the normal_orders field in the database.
	FieldNormalOrders = "normal_orders"
	// FieldExtraOrders holds the string denoting the extra_orders field in the database.
	FieldExtraOrders = "extra_orders"
	// FieldNormalTotal holds the string denoting the normal_total field in the database.
	FieldNormalTotal = "normal_total"
	// FieldNormalFee holds the string denoting the normal_fee field in the database.
	FieldNormalFee = "normal_fee"
	// FieldExtraTotal holds the string denoting the extra_total field in the database.
	FieldExtraTotal = "extra_total"
	// FieldExtraFee holds the string denoting the extra_fee field in the database.
	FieldExtraFee = "extra_fee"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgePost holds the string denoting the post edge name in mutations.
	EdgePost = "post"
	// Table holds the table name of the deliver in the database.
	Table = "delivers"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "delivers"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// PostTable is the table that holds the post relation/edge.
	PostTable = "delivers"
	// PostInverseTable is the table name for the Post entity.
	// It exists in this package in order to avoid circular dependency with the "post" package.
	PostInverseTable = "posts"
	// PostColumn is the table column denoting the post relation/edge.
	PostColumn = "post_id"
)

// Columns holds all SQL columns for deliver fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldPostID,
	FieldNormalOrders,
	FieldExtraOrders,
	FieldNormalTotal,
	FieldNormalFee,
	FieldExtraTotal,
	FieldExtraFee,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultNormalTotal holds the default value on creation for the "normal_total" field.
	DefaultNormalTotal float64
	// DefaultNormalFee holds the default value on creation for the "normal_fee" field.
	DefaultNormalFee float64
	// DefaultExtraTotal holds the default value on creation for the "extra_total" field.
	DefaultExtraTotal float64
	// DefaultExtraFee holds the default value on creation for the "extra_fee" field.
	DefaultExtraFee float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the Deliver queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPostID orders the results by the post_id field.
func ByPostID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostID, opts...).ToFunc()
}

// ByNormalTotal orders the results by the normal_total field.
func ByNormalTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNormalTotal, opts...).ToFunc()
}

// ByNormalFee orders the results by the normal_fee field.
func ByNormalFee(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNormalFee, opts...).ToFunc()
}

// ByExtraTotal orders the results by the extra_total field.
func ByExtraTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExtraTotal, opts...).ToFunc()
}

// ByExtraFee orders the results by the extra_fee field.
func ByExtraFee(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExtraFee, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByPostField orders the results by post field.
func ByPostField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPostStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newPostStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PostInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PostTable, PostColumn),
	)
}
