// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/billc-dev/tuango-go/ent/predicate"
	"github.com/billc-dev/tuango-go/ent/room"
	"github.com/billc-dev/tuango-go/ent/roomuser"
	"github.com/billc-dev/tuango-go/ent/user"
)

// RoomUserQuery is the builder for querying RoomUser entities.
type RoomUserQuery struct {
	config
	ctx        *QueryContext
	order      []roomuser.OrderOption
	inters     []Interceptor
	predicates []predicate.RoomUser
	withRoom   *RoomQuery
	withUser   *UserQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RoomUserQuery builder.
func (ruq *RoomUserQuery) Where(ps ...predicate.RoomUser) *RoomUserQuery {
	ruq.predicates = append(ruq.predicates, ps...)
	return ruq
}

// Limit the number of records to be returned by this query.
func (ruq *RoomUserQuery) Limit(limit int) *RoomUserQuery {
	ruq.ctx.Limit = &limit
	return ruq
}

// Offset to start from.
func (ruq *RoomUserQuery) Offset(offset int) *RoomUserQuery {
	ruq.ctx.Offset = &offset
	return ruq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ruq *RoomUserQuery) Unique(unique bool) *RoomUserQuery {
	ruq.ctx.Unique = &unique
	return ruq
}

// Order specifies how the records should be ordered.
func (ruq *RoomUserQuery) Order(o ...roomuser.OrderOption) *RoomUserQuery {
	ruq.order = append(ruq.order, o...)
	return ruq
}

// QueryRoom chains the current query on the "room" edge.
func (ruq *RoomUserQuery) QueryRoom() *RoomQuery {
	query := (&RoomClient{config: ruq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ruq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ruq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(roomuser.Table, roomuser.FieldID, selector),
			sqlgraph.To(room.Table, room.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, roomuser.RoomTable, roomuser.RoomColumn),
		)
		fromU = sqlgraph.SetNeighbors(ruq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (ruq *RoomUserQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: ruq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ruq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ruq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(roomuser.Table, roomuser.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, roomuser.UserTable, roomuser.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(ruq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RoomUser entity from the query.
// Returns a *NotFoundError when no RoomUser was found.
func (ruq *RoomUserQuery) First(ctx context.Context) (*RoomUser, error) {
	nodes, err := ruq.Limit(1).All(setContextOp(ctx, ruq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{roomuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ruq *RoomUserQuery) FirstX(ctx context.Context) *RoomUser {
	node, err := ruq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RoomUser ID from the query.
// Returns a *NotFoundError when no RoomUser ID was found.
func (ruq *RoomUserQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ruq.Limit(1).IDs(setContextOp(ctx, ruq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{roomuser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ruq *RoomUserQuery) FirstIDX(ctx context.Context) string {
	id, err := ruq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RoomUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RoomUser entity is found.
// Returns a *NotFoundError when no RoomUser entities are found.
func (ruq *RoomUserQuery) Only(ctx context.Context) (*RoomUser, error) {
	nodes, err := ruq.Limit(2).All(setContextOp(ctx, ruq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{roomuser.Label}
	default:
		return nil, &NotSingularError{roomuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ruq *RoomUserQuery) OnlyX(ctx context.Context) *RoomUser {
	node, err := ruq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RoomUser ID in the query.
// Returns a *NotSingularError when more than one RoomUser ID is found.
// Returns a *NotFoundError when no entities are found.
func (ruq *RoomUserQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ruq.Limit(2).IDs(setContextOp(ctx, ruq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{roomuser.Label}
	default:
		err = &NotSingularError{roomuser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ruq *RoomUserQuery) OnlyIDX(ctx context.Context) string {
	id, err := ruq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RoomUsers.
func (ruq *RoomUserQuery) All(ctx context.Context) ([]*RoomUser, error) {
	ctx = setContextOp(ctx, ruq.ctx, "All")
	if err := ruq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RoomUser, *RoomUserQuery]()
	return withInterceptors[[]*RoomUser](ctx, ruq, qr, ruq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ruq *RoomUserQuery) AllX(ctx context.Context) []*RoomUser {
	nodes, err := ruq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RoomUser IDs.
func (ruq *RoomUserQuery) IDs(ctx context.Context) (ids []string, err error) {
	if ruq.ctx.Unique == nil && ruq.path != nil {
		ruq.Unique(true)
	}
	ctx = setContextOp(ctx, ruq.ctx, "IDs")
	if err = ruq.Select(roomuser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ruq *RoomUserQuery) IDsX(ctx context.Context) []string {
	ids, err := ruq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ruq *RoomUserQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ruq.ctx, "Count")
	if err := ruq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ruq, querierCount[*RoomUserQuery](), ruq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ruq *RoomUserQuery) CountX(ctx context.Context) int {
	count, err := ruq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ruq *RoomUserQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ruq.ctx, "Exist")
	switch _, err := ruq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ruq *RoomUserQuery) ExistX(ctx context.Context) bool {
	exist, err := ruq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RoomUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ruq *RoomUserQuery) Clone() *RoomUserQuery {
	if ruq == nil {
		return nil
	}
	return &RoomUserQuery{
		config:     ruq.config,
		ctx:        ruq.ctx.Clone(),
		order:      append([]roomuser.OrderOption{}, ruq.order...),
		inters:     append([]Interceptor{}, ruq.inters...),
		predicates: append([]predicate.RoomUser{}, ruq.predicates...),
		withRoom:   ruq.withRoom.Clone(),
		withUser:   ruq.withUser.Clone(),
		// clone intermediate query.
		sql:  ruq.sql.Clone(),
		path: ruq.path,
	}
}

// WithRoom tells the query-builder to eager-load the nodes that are connected to
// the "room" edge. The optional arguments are used to configure the query builder of the edge.
func (ruq *RoomUserQuery) WithRoom(opts ...func(*RoomQuery)) *RoomUserQuery {
	query := (&RoomClient{config: ruq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ruq.withRoom = query
	return ruq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (ruq *RoomUserQuery) WithUser(opts ...func(*UserQuery)) *RoomUserQuery {
	query := (&UserClient{config: ruq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ruq.withUser = query
	return ruq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RoomID string `json:"room_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RoomUser.Query().
//		GroupBy(roomuser.FieldRoomID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ruq *RoomUserQuery) GroupBy(field string, fields ...string) *RoomUserGroupBy {
	ruq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RoomUserGroupBy{build: ruq}
	grbuild.flds = &ruq.ctx.Fields
	grbuild.label = roomuser.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RoomID string `json:"room_id,omitempty"`
//	}
//
//	client.RoomUser.Query().
//		Select(roomuser.FieldRoomID).
//		Scan(ctx, &v)
func (ruq *RoomUserQuery) Select(fields ...string) *RoomUserSelect {
	ruq.ctx.Fields = append(ruq.ctx.Fields, fields...)
	sbuild := &RoomUserSelect{RoomUserQuery: ruq}
	sbuild.label = roomuser.Label
	sbuild.flds, sbuild.scan = &ruq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RoomUserSelect configured with the given aggregations.
func (ruq *RoomUserQuery) Aggregate(fns ...AggregateFunc) *RoomUserSelect {
	return ruq.Select().Aggregate(fns...)
}

func (ruq *RoomUserQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ruq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ruq); err != nil {
				return err
			}
		}
	}
	for _, f := range ruq.ctx.Fields {
		if !roomuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ruq.path != nil {
		prev, err := ruq.path(ctx)
		if err != nil {
			return err
		}
		ruq.sql = prev
	}
	return nil
}

func (ruq *RoomUserQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RoomUser, error) {
	var (
		nodes       = []*RoomUser{}
		_spec       = ruq.querySpec()
		loadedTypes = [2]bool{
			ruq.withRoom != nil,
			ruq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RoomUser).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RoomUser{config: ruq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(ruq.modifiers) > 0 {
		_spec.Modifiers = ruq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ruq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ruq.withRoom; query != nil {
		if err := ruq.loadRoom(ctx, query, nodes, nil,
			func(n *RoomUser, e *Room) { n.Edges.Room = e }); err != nil {
			return nil, err
		}
	}
	if query := ruq.withUser; query != nil {
		if err := ruq.loadUser(ctx, query, nodes, nil,
			func(n *RoomUser, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ruq *RoomUserQuery) loadRoom(ctx context.Context, query *RoomQuery, nodes []*RoomUser, init func(*RoomUser), assign func(*RoomUser, *Room)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*RoomUser)
	for i := range nodes {
		if nodes[i].RoomID == nil {
			continue
		}
		fk := *nodes[i].RoomID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(room.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "room_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (ruq *RoomUserQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*RoomUser, init func(*RoomUser), assign func(*RoomUser, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*RoomUser)
	for i := range nodes {
		if nodes[i].UserID == nil {
			continue
		}
		fk := *nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ruq *RoomUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ruq.querySpec()
	if len(ruq.modifiers) > 0 {
		_spec.Modifiers = ruq.modifiers
	}
	_spec.Node.Columns = ruq.ctx.Fields
	if len(ruq.ctx.Fields) > 0 {
		_spec.Unique = ruq.ctx.Unique != nil && *ruq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ruq.driver, _spec)
}

func (ruq *RoomUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(roomuser.Table, roomuser.Columns, sqlgraph.NewFieldSpec(roomuser.FieldID, field.TypeString))
	_spec.From = ruq.sql
	if unique := ruq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ruq.path != nil {
		_spec.Unique = true
	}
	if fields := ruq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, roomuser.FieldID)
		for i := range fields {
			if fields[i] != roomuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if ruq.withRoom != nil {
			_spec.Node.AddColumnOnce(roomuser.FieldRoomID)
		}
		if ruq.withUser != nil {
			_spec.Node.AddColumnOnce(roomuser.FieldUserID)
		}
	}
	if ps := ruq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ruq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ruq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ruq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ruq *RoomUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ruq.driver.Dialect())
	t1 := builder.Table(roomuser.Table)
	columns := ruq.ctx.Fields
	if len(columns) == 0 {
		columns = roomuser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ruq.sql != nil {
		selector = ruq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ruq.ctx.Unique != nil && *ruq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range ruq.modifiers {
		m(selector)
	}
	for _, p := range ruq.predicates {
		p(selector)
	}
	for _, p := range ruq.order {
		p(selector)
	}
	if offset := ruq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ruq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ruq *RoomUserQuery) Modify(modifiers ...func(s *sql.Selector)) *RoomUserSelect {
	ruq.modifiers = append(ruq.modifiers, modifiers...)
	return ruq.Select()
}

// RoomUserGroupBy is the group-by builder for RoomUser entities.
type RoomUserGroupBy struct {
	selector
	build *RoomUserQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rugb *RoomUserGroupBy) Aggregate(fns ...AggregateFunc) *RoomUserGroupBy {
	rugb.fns = append(rugb.fns, fns...)
	return rugb
}

// Scan applies the selector query and scans the result into the given value.
func (rugb *RoomUserGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rugb.build.ctx, "GroupBy")
	if err := rugb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoomUserQuery, *RoomUserGroupBy](ctx, rugb.build, rugb, rugb.build.inters, v)
}

func (rugb *RoomUserGroupBy) sqlScan(ctx context.Context, root *RoomUserQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rugb.fns))
	for _, fn := range rugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rugb.flds)+len(rugb.fns))
		for _, f := range *rugb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rugb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rugb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RoomUserSelect is the builder for selecting fields of RoomUser entities.
type RoomUserSelect struct {
	*RoomUserQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rus *RoomUserSelect) Aggregate(fns ...AggregateFunc) *RoomUserSelect {
	rus.fns = append(rus.fns, fns...)
	return rus
}

// Scan applies the selector query and scans the result into the given value.
func (rus *RoomUserSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rus.ctx, "Select")
	if err := rus.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoomUserQuery, *RoomUserSelect](ctx, rus.RoomUserQuery, rus, rus.inters, v)
}

func (rus *RoomUserSelect) sqlScan(ctx context.Context, root *RoomUserQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rus.fns))
	for _, fn := range rus.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rus.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (rus *RoomUserSelect) Modify(modifiers ...func(s *sql.Selector)) *RoomUserSelect {
	rus.modifiers = append(rus.modifiers, modifiers...)
	return rus
}
